[DataBase]
host=109.81.121.193
database=adam
port=3306
user=adam
pass=olovrant877
[Chat]
Max_QuedMesseges=5
[Login]
timeout=120
[System]
debugmode=true
[Player]
Starting_Coins=50
Starting_Xp=0
Starting_Lvl=1
[Stats]
DIRT=10
[ChatChannel]
plCountBasic=2
plCountVip=15
#Max PLayer Count
worldPlCount=15