name: MorgulPlugin
main: cz.opt.morgulplugin.MorgulPlugin
version: 0.01

commands:
   info:
      description: This is a info command.
      usage: /<command>
      permission: MorgulPlugin.info
      permission-message: You don't have permission for MorgulPlugin.
   login:
      description: Login command.
      usage: /<command> [password]
      permission: MorgulPlugin.login
      permission-message: You don't have permission for MorgulPlugin.
   economy:
      description: Economy command.
      usage: /<command> [function] [function argument]
      permission: MorgulPlugin.economy
      permission-message: You don't have permission for MorgulPlugin. 
   pay:
      description: Economy command.
      usage: /<command> [function argument]
      permission: MorgulPlugin.economy
      permission-message: You don't have permission for MorgulPlugin.
   chat:
      description: Chat command.
      usage: /<command> [function] [function argument]
      permission: MorgulPlugin.chat
      permission-message: You don't have permission for MorgulPlugin.
   w:
      description: Chat command.
      usage: /<command> [player] [message]
      permission: MorgulPlugin.whisper
      permission-message: You don't have permission for MorgulPlugin.
   msg:
      description: Chat command.
      usage: /<command> [player] [message]
      permission: MorgulPlugin.whisper
      permission-message: You don't have permission for MorgulPlugin.
   whisper:
      description: Chat command.
      usage: /<command> [player] [message]
      permission: MorgulPlugin.whisper
      permission-message: You don't have permission for MorgulPlugin.